services:
  - type: web
    name: edunet-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://ADITH003:ADITH003@cluster0.sjqo6gz.mongodb.net/classroom?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "edunet_super_secret_jwt_key_2024"
      - key: CLIENT_URL
        value: "https://edu-net-frontend.vercel.app"
      - key: PORT
        value: "10000"
